/**
 * Derive the CV model's identity from the model bytes and write it where both the app
 * and the service worker can read it. Runs on postinstall/predev/prebuild.
 *
 * Two problems this solves, both from the same hash:
 *
 *  1. Cache poisoning. `/models/best.onnx` was a fixed URL served with
 *     `immutable, max-age=31536000` (next.config.mjs) AND cached cache-first-forever by
 *     sw.js. A redeployed model was therefore unreachable behind two cache layers — the
 *     "content-addressed by our build" claim in next.config.mjs was simply false. Putting
 *     the digest in the query string makes it true: new bytes → new cache key.
 *
 *  2. Provenance. A detection is only reproducible if you know which weights produced it.
 *     The scan binds this version into its ClientCondition so the backend can reject a
 *     condition produced by weights it doesn't recognise.
 *
 * The hash is of the file the browser actually downloads, so it cannot drift from reality.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const modelPath = join(here, "..", "public", "models", "best.onnx");
const outPath = join(here, "..", "lib", "cv", "model-version.json");

// The ORT build is part of the inference contract — a different runtime can produce
// different floats from identical weights — so it is versioned alongside the model.
// copy-ort.mjs derives this same value independently from the same package.json, so the
// two scripts agree without sharing state or caring which runs first.
const ortVersion = JSON.parse(
  readFileSync(join(here, "..", "node_modules", "onnxruntime-web", "package.json"), "utf-8"),
).version;

let sha256;
try {
  sha256 = createHash("sha256").update(readFileSync(modelPath)).digest("hex");
} catch (err) {
  // Fail loudly. A silent fallback here would let a build ship a model whose version
  // string doesn't match its bytes — exactly the untraceable state this file exists to
  // prevent. Better to break the build than to lie about which model is deployed.
  console.error(`[cv-version] cannot read ${modelPath}: ${err.message}`);
  process.exit(1);
}

const version = sha256.slice(0, 12);

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  JSON.stringify(
    {
      _comment: "GENERATED by scripts/cv-version.mjs — do not edit. Derived from public/models/best.onnx.",
      modelSha256: sha256,
      modelVersion: version,
      // Query string, not a renamed file: the 44 MB blob stays a single committed artifact
      // while every cache layer (HTTP, SW) keys on the digest.
      modelUrl: `/models/best.onnx?v=${version}`,
      ortVersion,
      // Versioned directory (copy-ort.mjs writes here). Without it, an ORT upgrade ships
      // new wasm bytes under the old URL, which sw.js caches first-and-forever and
      // next.config.mjs marks immutable for a year — silently pinning users to the old
      // runtime. public/ort/ is gitignored and rebuilt, so the path is free to move.
      ortDir: `/ort/${ortVersion}/`,
    },
    null,
    2,
  ) + "\n",
  "utf-8",
);

console.log(
  `[cv-version] model=${version}… ort=${ortVersion} → lib/cv/model-version.json`,
);
