import { jsPDF } from "jspdf";
import type { ValuationResult } from "./types";
import { aed, km, titleCase } from "./utils";
import { resolveReportPlain } from "./report";

/**
 * Phase K — dealer branding. A dealer on the paid tier can put their own name, colour and
 * logo on the report they hand to a customer; the underlying figures are untouched, and the
 * AutoValuate attribution stays in the footer so the report can never be passed off as an
 * independent appraisal it isn't.
 */
export interface Brand {
  name: string;
  /** accent colour as [r,g,b] */
  accent?: [number, number, number];
  /** logo as a data: URL (PNG/JPEG) */
  logoDataUrl?: string;
}

const DEFAULT_BRAND: Brand = { name: "AutoValuate", accent: [245, 166, 35] };

/** Build a clean, text-based PDF of the valuation report (no screenshotting). */
export function downloadReportPdf(r: ValuationResult, brand: Brand = DEFAULT_BRAND) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  let y = M;

  const v = r.vehicle;
  const val = r.valuation;

  const line = (text: string, size = 10, opts: { bold?: boolean; color?: [number, number, number]; gap?: number } = {}) => {
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(...(opts.color ?? [30, 41, 59]));
    const wrapped = doc.splitTextToSize(text, W - 2 * M);
    for (const ln of wrapped) {
      if (y > 780) { doc.addPage(); y = M; }
      doc.text(ln, M, y);
      y += size + 4;
    }
    y += opts.gap ?? 0;
  };
  const rule = () => { doc.setDrawColor(226, 232, 240); doc.line(M, y, W - M, y); y += 14; };

  // header (white-labelled when a dealer brand is supplied)
  const accent = brand.accent ?? DEFAULT_BRAND.accent!;
  doc.setFillColor(15, 22, 32); doc.rect(0, 0, W, 70, "F");
  let textX = M;
  if (brand.logoDataUrl) {
    try {
      doc.addImage(brand.logoDataUrl, "PNG", M, 18, 34, 34);
      textX = M + 44;
    } catch { /* a bad logo must never break the report */ }
  }
  doc.setFont("helvetica", "bold"); doc.setFontSize(18); doc.setTextColor(...accent);
  doc.text(brand.name || DEFAULT_BRAND.name, textX, 40);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(200, 210, 220);
  doc.text("valuation report", textX, 55);
  y = 96;

  line(`${v.year} ${titleCase(String(v.make))} ${titleCase(String(v.model))}`, 16, { bold: true });
  line(`${km(v.kilometers)}  ·  ${v.regionalSpecs ?? "GCC"}  ·  ${v.bodyType ?? ""}  ·  ${v.city ?? ""}`, 10, { color: [100, 116, 139], gap: 8 });
  rule();

  line("Estimated fair-market value", 11, { bold: true });
  line(`${aed(val.price_low_aed)}  —  ${aed(val.price_high_aed)}`, 20, { bold: true, color: accent });
  line(`Mid-point ${aed(val.price_mid_aed)}  ·  ~${Math.round(val.interval_coverage * 100)}% held-out interval  ·  model median error ${val.model_meta.cv_median_ape_pct}%`, 9, { color: [100, 116, 139], gap: 10 });

  line("Why this price (top factors)", 11, { bold: true });
  for (const f of val.explanation.top_factors.slice(0, 5)) {
    const impact = Math.round(f.approx_aed_impact);
    line(`• ${titleCase(String(f.feature))}: ${impact >= 0 ? "+" : ""}${impact.toLocaleString()} AED`, 10);
  }
  y += 6; rule();

  line("Condition", 11, { bold: true });
  line(r.condition.cv_available
    ? `Condition score ${r.condition.condition_score}/100 from ${r.condition.photos_assessed} photo(s).`
    : "No photo-based damage assessment was performed; the estimate assumes market-typical condition.", 10, { gap: 10 });

  line("Comparable listings", 11, { bold: true });
  for (const c of r.comparables.slice(0, 5)) {
    line(`• ${c.year} ${titleCase(String(c.make))} ${titleCase(String(c.model))}, ${km(c.kilometers)} — ${aed(c.price_aed)}  (#${c.listing_id})`, 10);
  }
  y += 6; rule();

  line("Summary", 11, { bold: true });
  for (const para of resolveReportPlain(r).split("\n\n")) {
    line(para, 10, { gap: 6 });
  }

  line("Confidence", 11, { bold: true, color: accent });
  line(r.confidence.statement, 9, { color: [100, 116, 139], gap: 6 });

  doc.setFontSize(8); doc.setTextColor(150, 160, 170);
  // Attribution is never removable: a white-labelled report must still disclose what produced it.
  doc.text(
    brand.name && brand.name !== DEFAULT_BRAND.name
      ? `Automated estimate — not a certified appraisal. Powered by AutoValuate Intelligence for ${brand.name}.`
      : "Automated estimate — not a certified appraisal. Generated by AutoValuate Intelligence.",
    M, 812);

  const name = `AutoValuate_${v.year}_${v.make}_${v.model}`.replace(/[^\w]+/g, "_");
  doc.save(`${name}.pdf`);
}
